"""empty message

Revision ID: dc88bba5ab5d
Revises: 
Create Date: 2018-10-19 11:30:54.304349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc88bba5ab5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_sales_channel_count')
    op.drop_table('tbl_sales_time_count')
    op.drop_table('tbl_user_score_count')
    op.alter_column('tbl_sales_channel_count_copy', 'fld_phone_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.alter_column('tbl_sales_channel_count_copy', 'fld_sale_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('tbl_sales_channel_count_copy', 'fld_sales_channel',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.create_unique_constraint(None, 'tbl_sales_channel_count_copy', ['fld_phone_name'])
    op.create_unique_constraint(None, 'tbl_sales_channel_count_copy', ['fld_sale_count'])
    op.create_unique_constraint(None, 'tbl_sales_channel_count_copy', ['fld_sales_channel'])
    op.alter_column('tbl_sales_time_count_copy', 'fld_phone_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.alter_column('tbl_sales_time_count_copy', 'fld_sale_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('tbl_sales_time_count_copy', 'fld_sales_time',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_unique_constraint(None, 'tbl_sales_time_count_copy', ['fld_sale_count'])
    op.create_unique_constraint(None, 'tbl_sales_time_count_copy', ['fld_sales_time'])
    op.create_unique_constraint(None, 'tbl_sales_time_count_copy', ['fld_phone_name'])
    op.alter_column('tbl_user_score_count_copy', 'fld_phone_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.alter_column('tbl_user_score_count_copy', 'fld_user_score',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.create_unique_constraint(None, 'tbl_user_score_count_copy', ['fld_phone_name'])
    op.create_unique_constraint(None, 'tbl_user_score_count_copy', ['fld_user_score'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_user_score_count_copy', type_='unique')
    op.drop_constraint(None, 'tbl_user_score_count_copy', type_='unique')
    op.alter_column('tbl_user_score_count_copy', 'fld_user_score',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('tbl_user_score_count_copy', 'fld_phone_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.drop_constraint(None, 'tbl_sales_time_count_copy', type_='unique')
    op.drop_constraint(None, 'tbl_sales_time_count_copy', type_='unique')
    op.drop_constraint(None, 'tbl_sales_time_count_copy', type_='unique')
    op.alter_column('tbl_sales_time_count_copy', 'fld_sales_time',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('tbl_sales_time_count_copy', 'fld_sale_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('tbl_sales_time_count_copy', 'fld_phone_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.drop_constraint(None, 'tbl_sales_channel_count_copy', type_='unique')
    op.drop_constraint(None, 'tbl_sales_channel_count_copy', type_='unique')
    op.drop_constraint(None, 'tbl_sales_channel_count_copy', type_='unique')
    op.alter_column('tbl_sales_channel_count_copy', 'fld_sales_channel',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.alter_column('tbl_sales_channel_count_copy', 'fld_sale_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('tbl_sales_channel_count_copy', 'fld_phone_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.create_table('tbl_user_score_count',
    sa.Column('fld_index', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('fld_phone_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('fld_user_score', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('fld_index'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tbl_sales_time_count',
    sa.Column('fld_index', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('fld_phone_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('fld_sales_time', sa.DATE(), nullable=False),
    sa.Column('fld_sale_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('fld_index'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tbl_sales_channel_count',
    sa.Column('fld_index', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('fld_phone_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('fld_sales_channel', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('fld_sale_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('fld_index'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
